Repository google/cadvisor, pull requests merged in 2020-09, with the labels that each got.

#2578 Add perf event grouping.
  docs/runtime_options.md
  manager/manager.go
  perf/collector_libpfm.go
  perf/collector_libpfm_test.go
  perf/config.go
  perf/config_test.go
  perf/manager_libpfm.go
  perf/manager_libpfm_test.go
  perf/manager_no_libpfm.go
  perf/testing/grouped.json
  perf/testing/perf-non-hardware.json
  perf/testing/perf.json
  perf/types_libpfm.go
  perf/uncore_libpfm.go
  perf/uncore_libpfm_test.go
  utils/sysinfo/sysinfo.go
  utils/sysinfo/sysinfo_test.go
Labels: ok-to-test

#2665 add clean operation when watchForNewContainers/Start failed
  container/raw/watcher.go
  manager/manager.go
Labels: ok-to-test

#2646 Fixed https proxy issue by installing 'full' wget in Docker alpine-based build stage
  deploy/Dockerfile
Labels: ok-to-test

#2644 Use perf attributes from unix lib.
  go.mod
  go.sum
  perf/collector_libpfm.go
  perf/types_libpfm.go
Labels: ok-to-test

#2612 Add stats to stdout storage
  cmd/internal/storage/stdout/stdout.go
Labels: ok-to-test

#2638 Add stats to statsd storage
  cmd/internal/storage/statsd/statsd.go
Labels: ok-to-test

#1594 chore: add storage_driver_buffer_duration in Influxdb storage docs
  docs/storage/influxdb.md
Labels: area/documentation

#2683 Add flags that were not previously published
  docs/runtime_options.md
Labels: cla: yes
