Repository google/cadvisor, pull requests merged in 2021-03, with the labels that each got.

#2811 Remove trailing \0 from values read from ppc64le device-tree.
  utils/sysfs/sysfs.go
Labels: cla: yes, ok-to-test

#2817 Fix oomparser regex for kernels 5.0 and higher
  utils/oomparser/oomparser.go
  utils/oomparser/oomparser_test.go
Labels: cla: yes, ok-to-test

#2810 Fix memory stats for cgroup v2
  container/libcontainer/handler.go
Labels: cla: yes, ok-to-test

#2801 Allow gathering of stats for root cgroup on v2
  container/libcontainer/handler.go
Labels: cla: yes, ok-to-test

#2800 Update heuristic for container creation time
  container/common/helpers.go
Labels: cla: yes, ok-to-test

#2796 Add cgroup_memory_migrate metric
  cmd/cadvisor.go
  cmd/cadvisor_test.go
  container/factory.go
  container/libcontainer/handler.go
  docs/runtime_options.md
  docs/storage/prometheus.md
  info/v1/container.go
  metrics/prometheus.go
  metrics/prometheus_fake.go
  metrics/testdata/prometheus_metrics
Labels: cla: yes, ok-to-test

#2818 Bump golang to 1.16
  .github/workflows/test.yml
  Makefile
  build/integration-in-docker.sh
  build/unit-in-container.sh
  cmd/go.sum
  deploy/canary/Dockerfile
Labels: cla: yes

#2774 ADD "disable_specific_metrics" which can remove specific metric by name or regex
  cmd/cadvisor.go
  cmd/internal/http/handlers.go
  manager/manager.go
  metrics/deny_list.go
  metrics/deny_list_test.go
  metrics/prometheus.go
  metrics/prometheus_machine.go
  metrics/prometheus_machine_test.go
  metrics/prometheus_test.go
  metrics/testdata/allow_metrics
  metrics/testdata/deny_metrics
  metrics/testdata/prometheus_machine_metrics_denylist
  metrics/testdata/prometheus_metrics_denylist
Labels: cla: yes, ok-to-test

#2768 Added support for filesystem metrics on Docker
  container/docker/handler.go
  container/docker/handler_test.go
  fs/fs.go
  fs/fs_test.go
  fs/types.go
Labels: cla: yes, ok-to-test

#2825 update docs/runtime_options.md with the new flag 'disable_specific_me…
  docs/runtime_options.md
Labels: cla: yes, needs-ok-to-test

#2827 Revert "ADD "disable_specific_metrics" which can remove specific metric by name or regex"
  cmd/cadvisor.go
  cmd/internal/http/handlers.go
  manager/manager.go
  metrics/deny_list.go
  metrics/deny_list_test.go
  metrics/prometheus.go
  metrics/prometheus_machine.go
  metrics/prometheus_machine_test.go
  metrics/prometheus_test.go
  metrics/testdata/allow_metrics
  metrics/testdata/deny_metrics
  metrics/testdata/prometheus_machine_metrics_denylist
  metrics/testdata/prometheus_metrics_denylist
Labels: cla: yes

#2826 Bump containerd to 1.4.4
  cmd/go.sum
  go.mod
  go.sum
Labels: cla: yes

#2828 Conditionally gathering FS usage metrics.
  container/docker/factory.go
Labels: cla: yes

#2830 Update changelog for 0.39.0
  CHANGELOG.md
Labels: cla: yes

#2829 Expose OOM event count to prometheus
  cmd/cadvisor.go
  cmd/cadvisor_test.go
  container/factory.go
  info/v1/container.go
  manager/container.go
  manager/manager.go
  metrics/prometheus.go
  metrics/testdata/prometheus_metrics
Labels: cla: yes, ok-to-test

#2832 Add missing python3 in Dockerfile.
  deploy/Dockerfile
Labels: cla: yes, ok-to-test

#2837 Fix read "max" value for cgroup v2
  container/common/helpers.go
Labels: cla: yes, ok-to-test

#2836 Add support for non btrfs devices in GetDirFsDevice
  fs/fs.go
Labels: cla: yes, ok-to-test

#2839 helpers: fix reading cpu stats on cgroup v2
  container/common/helpers.go
  container/common/helpers_test.go
  container/common/test_resources/cgroup_v1/test1/cpu/cpu.cfs_period_us
  container/common/test_resources/cgroup_v1/test1/cpu/cpu.cfs_quota_us
  container/common/test_resources/cgroup_v1/test1/cpu/cpu.shares
  container/common/test_resources/cgroup_v1/test1/cpuset/cpuset.cpus
  container/common/test_resources/cgroup_v1/test1/memory/memory.limit_in_bytes
  container/common/test_resources/cgroup_v1/test1/memory/memory.memsw.limit_in_bytes
  container/common/test_resources/cgroup_v1/test1/memory/memory.soft_limit_in_bytes
  container/common/test_resources/cgroup_v1/test1/pids/pids.max
  container/common/test_resources/cgroup_v2/test1/cpu.max
  container/common/test_resources/cgroup_v2/test1/cpu.weight
  container/common/test_resources/cgroup_v2/test1/cpuset.cpus.effective
  container/common/test_resources/cgroup_v2/test1/memory.high
  container/common/test_resources/cgroup_v2/test1/memory.max
  container/common/test_resources/cgroup_v2/test1/memory.swap.max
  container/common/test_resources/cgroup_v2/test1/pids.max
  container/common/test_resources/cgroup_v2/test2/cpu.max
  container/common/test_resources/cgroup_v2/test2/cpu.weight
  container/common/test_resources/cgroup_v2/test2/memory.high
  container/common/test_resources/cgroup_v2/test2/memory.max
  container/common/test_resources/cgroup_v2/test2/memory.swap.max
  container/common/test_resources/cgroup_v2/test2/pids.max
Labels: cla: yes, ok-to-test
