Repository google/cadvisor, pull requests merged in 2021-09, with the labels that each got.

#2930 feat: add container whitelisted envs as metrics labels.
  metrics/prometheus.go
  metrics/prometheus_test.go
  metrics/testdata/prometheus_metrics_whitelist_filtered
Labels: ok-to-test, cla: yes

#2934 if docker can't connect during InitializeFSContext , do not add image dev info to real fs info label cache
  fs/fs.go
  fs/fs_test.go
Labels: ok-to-test, cla: yes

#2937 deps: upgrade runc to 1.0.2, revert containerd to v1.4.4
  cmd/go.sum
  go.mod
  go.sum
Labels: cla: yes

#2939 Bump to containerd v1.4.9
  cmd/go.sum
  go.mod
  go.sum
Labels: cla: yes

#2942 Merge master changes back into containerd-cri
  build/integration.sh
  cmd/cadvisor.go
  cmd/go.sum
  cmd/internal/container/mesos/factory.go
  cmd/internal/container/mesos/handler.go
  cmd/internal/container/mesos/handler_test.go
  container/common/fsHandler.go
  container/containerd/factory.go
  container/containerd/handler.go
  container/containerd/handler_test.go
  container/crio/factory.go
  container/crio/handler.go
  container/crio/handler_test.go
  container/docker/factory.go
  container/docker/handler.go
  container/docker/handler_test.go
  container/factory.go
  container/factory_test.go
  container/libcontainer/helpers.go
  container/raw/factory.go
  container/systemd/factory.go
  container/testing/mock_handler.go
  docs/runtime_options.md
  fs/fs.go
  fs/fs_test.go
  go.mod
  go.sum
  integration/runner/runner.go
  manager/manager.go
  metrics/prometheus.go
  metrics/prometheus_test.go
  metrics/testdata/prometheus_metrics_whitelist_filtered
Labels: cla: no

#2943 Run `make tidy` on containerd-cri
  cmd/go.sum
  go.sum
Labels: cla: yes

#2793 Add mon_group support for resctrl.
  cmd/cadvisor.go
  container/raw/factory.go
  docs/runtime_options.md
  info/v1/machine.go
  machine/info.go
  machine/machine.go
  machine/topology_test.go
  manager/container.go
  manager/manager.go
  resctrl/collector.go
  resctrl/collector_test.go
  resctrl/manager.go
  resctrl/manager_test.go
  resctrl/testing/tasks_empty
  resctrl/testing/tasks_invalid
  resctrl/testing/tasks_one
  resctrl/testing/tasks_two
  resctrl/utils.go
  resctrl/utils_test.go
Labels: ok-to-test, cla: yes

#2944 Remove cri-api from go.mod
  cmd/go.mod
  cmd/go.sum
  container/containerd/client.go
  container/containerd/client_test.go
  container/containerd/handler_test.go
  go.mod
  go.sum
Labels: ok-to-test, cla: yes

#2936 Add missing file system metrics in containerd handler
  container/common/fsHandler.go
  container/containerd/client.go
  container/containerd/client_test.go
  container/containerd/factory_test.go
  container/containerd/handler.go
  container/containerd/handler_test.go
  container/crio/handler.go
  container/docker/handler.go
Labels: ok-to-test, cla: yes

#2945 Support git tag with `rc` when doing releases
  build/release.sh
Labels: cla: yes

#2946 Prepend rootfs to the paths in containerd handler
  container/containerd/handler.go
Labels: needs-ok-to-test, cla: yes
