Repository google/cadvisor, pull requests merged in 2021-02, with the labels that each got.

#2799 Fix incorrect CPU topology on single NUMA and multi socket platform.
  utils/sysinfo/sysinfo.go
  utils/sysinfo/sysinfo_test.go
Labels: cla: yes, ok-to-test

#2805 sched_getaffinity does not return number of online CPUs
  container/libcontainer/handler.go
  container/libcontainer/handler_test.go
Labels: cla: yes

#2795 Add container_blkio_device_usage metric
  docs/storage/prometheus.md
  metrics/prometheus.go
  metrics/prometheus_fake.go
  metrics/testdata/prometheus_metrics
Labels: cla: yes, ok-to-test

#2674 Add libipmctl to the docker image.
  deploy/Dockerfile
  docs/development/build.md
Labels: cla: yes, ok-to-test

#2806 Porting fixes to #2792 and #2798 to v0.38
  container/libcontainer/handler.go
  container/libcontainer/handler_test.go
  utils/sysinfo/sysinfo.go
  utils/sysinfo/sysinfo_test.go
Labels: cla: yes

#2807 Porting fixes to #2792 and #2798 to v0.37
  container/libcontainer/handler.go
  container/libcontainer/handler_test.go
  utils/sysinfo/sysinfo.go
  utils/sysinfo/sysinfo_test.go
Labels: cla: yes

#2809 bump runc to v1.0.0-rc93
  cmd/go.sum
  go.mod
  go.sum
Labels: cla: yes, needs-ok-to-test
