Repository google/cadvisor, pull requests merged in 2022-01, with the labels that each got.

#3038 Backporting #2868 on release v0.39.x
  manager/manager.go
Labels: needs-ok-to-test

#3014 Bump k/utils to v0.0.0-20211116205334-6203023598ed
  cmd/go.mod
  cmd/go.sum
  go.mod
  go.sum
Labels: ok-to-test, cla: yes

#3034 go.mod: github.com/moby/term v0.0.0-20210619224110-3f7ff695adc6
  cmd/go.sum
  go.mod
  go.sum
Labels: ok-to-test

#3030 Fix process metrics collection in cgroup v2
  container/common/helpers.go
  container/libcontainer/handler.go
Labels: ok-to-test

#3043 manager: fix determining selfContainer name
  manager/manager.go
Labels: ok-to-test

#3018 Move `ErrDeviceNotInPartitionsMap` outside of the build constraints
  fs/fs.go
  fs/types.go
Labels: ok-to-test, cla: yes

#3031 deps: update runc to 1.1.0-rc.1
  cmd/go.sum
  container/libcontainer/helpers.go
  go.mod
  go.sum
  resctrl/utils.go
  resctrl/utils_test.go
Labels: ok-to-test

#3048 vendor: bump runc to 1.1.0
  cmd/go.sum
  go.mod
  go.sum
Labels: needs-ok-to-test
